/*
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.limix.awx.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CredentialInputSource
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-25T17:26:39.970+08:00[Asia/Shanghai]")
public class CredentialInputSource {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("related")
  private Object related = null;

  @SerializedName("summary_fields")
  private Object summaryFields = null;

  @SerializedName("created")
  private String created = null;

  @SerializedName("modified")
  private String modified = null;

  @SerializedName("description")
  private String description = "";

  @SerializedName("input_field_name")
  private String inputFieldName = null;

  @SerializedName("metadata")
  private Object metadata = null;

  @SerializedName("target_credential")
  private Integer targetCredential = null;

  @SerializedName("source_credential")
  private Integer sourceCredential = null;

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public CredentialInputSource related(Object related) {
    this.related = related;
    return this;
  }

   /**
   * Get related
   * @return related
  **/
  @Schema(description = "")
  public Object getRelated() {
    return related;
  }

  public void setRelated(Object related) {
    this.related = related;
  }

  public CredentialInputSource summaryFields(Object summaryFields) {
    this.summaryFields = summaryFields;
    return this;
  }

   /**
   * Get summaryFields
   * @return summaryFields
  **/
  @Schema(description = "")
  public Object getSummaryFields() {
    return summaryFields;
  }

  public void setSummaryFields(Object summaryFields) {
    this.summaryFields = summaryFields;
  }

   /**
   * Get created
   * @return created
  **/
  @Schema(description = "")
  public String getCreated() {
    return created;
  }

   /**
   * Get modified
   * @return modified
  **/
  @Schema(description = "")
  public String getModified() {
    return modified;
  }

  public CredentialInputSource description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CredentialInputSource inputFieldName(String inputFieldName) {
    this.inputFieldName = inputFieldName;
    return this;
  }

   /**
   * Get inputFieldName
   * @return inputFieldName
  **/
  @Schema(required = true, description = "")
  public String getInputFieldName() {
    return inputFieldName;
  }

  public void setInputFieldName(String inputFieldName) {
    this.inputFieldName = inputFieldName;
  }

  public CredentialInputSource metadata(Object metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @Schema(description = "")
  public Object getMetadata() {
    return metadata;
  }

  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }

  public CredentialInputSource targetCredential(Integer targetCredential) {
    this.targetCredential = targetCredential;
    return this;
  }

   /**
   * Get targetCredential
   * @return targetCredential
  **/
  @Schema(required = true, description = "")
  public Integer getTargetCredential() {
    return targetCredential;
  }

  public void setTargetCredential(Integer targetCredential) {
    this.targetCredential = targetCredential;
  }

  public CredentialInputSource sourceCredential(Integer sourceCredential) {
    this.sourceCredential = sourceCredential;
    return this;
  }

   /**
   * Get sourceCredential
   * @return sourceCredential
  **/
  @Schema(required = true, description = "")
  public Integer getSourceCredential() {
    return sourceCredential;
  }

  public void setSourceCredential(Integer sourceCredential) {
    this.sourceCredential = sourceCredential;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CredentialInputSource credentialInputSource = (CredentialInputSource) o;
    return Objects.equals(this.id, credentialInputSource.id) &&
        Objects.equals(this.type, credentialInputSource.type) &&
        Objects.equals(this.url, credentialInputSource.url) &&
        Objects.equals(this.related, credentialInputSource.related) &&
        Objects.equals(this.summaryFields, credentialInputSource.summaryFields) &&
        Objects.equals(this.created, credentialInputSource.created) &&
        Objects.equals(this.modified, credentialInputSource.modified) &&
        Objects.equals(this.description, credentialInputSource.description) &&
        Objects.equals(this.inputFieldName, credentialInputSource.inputFieldName) &&
        Objects.equals(this.metadata, credentialInputSource.metadata) &&
        Objects.equals(this.targetCredential, credentialInputSource.targetCredential) &&
        Objects.equals(this.sourceCredential, credentialInputSource.sourceCredential);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, url, related, summaryFields, created, modified, description, inputFieldName, metadata, targetCredential, sourceCredential);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CredentialInputSource {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    summaryFields: ").append(toIndentedString(summaryFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    inputFieldName: ").append(toIndentedString(inputFieldName)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    targetCredential: ").append(toIndentedString(targetCredential)).append("\n");
    sb.append("    sourceCredential: ").append(toIndentedString(sourceCredential)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
