/*
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.limix.awx.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * OrganizationCredentialSerializerCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-25T17:26:39.970+08:00[Asia/Shanghai]")
public class OrganizationCredentialSerializerCreate {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("related")
  private Object related = null;

  @SerializedName("summary_fields")
  private Object summaryFields = null;

  @SerializedName("created")
  private String created = null;

  @SerializedName("modified")
  private String modified = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = "";

  @SerializedName("organization")
  private Integer organization = null;

  @SerializedName("credential_type")
  private Integer credentialType = null;

  @SerializedName("managed")
  private String managed = null;

  @SerializedName("inputs")
  private Object inputs = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("cloud")
  private String cloud = null;

  @SerializedName("kubernetes")
  private String kubernetes = null;

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public OrganizationCredentialSerializerCreate related(Object related) {
    this.related = related;
    return this;
  }

   /**
   * Get related
   * @return related
  **/
  @Schema(description = "")
  public Object getRelated() {
    return related;
  }

  public void setRelated(Object related) {
    this.related = related;
  }

  public OrganizationCredentialSerializerCreate summaryFields(Object summaryFields) {
    this.summaryFields = summaryFields;
    return this;
  }

   /**
   * Get summaryFields
   * @return summaryFields
  **/
  @Schema(description = "")
  public Object getSummaryFields() {
    return summaryFields;
  }

  public void setSummaryFields(Object summaryFields) {
    this.summaryFields = summaryFields;
  }

   /**
   * Get created
   * @return created
  **/
  @Schema(description = "")
  public String getCreated() {
    return created;
  }

   /**
   * Get modified
   * @return modified
  **/
  @Schema(description = "")
  public String getModified() {
    return modified;
  }

  public OrganizationCredentialSerializerCreate name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OrganizationCredentialSerializerCreate description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OrganizationCredentialSerializerCreate organization(Integer organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Inherit permissions from organization roles. If provided on creation, do not give either user or team.
   * @return organization
  **/
  @Schema(description = "Inherit permissions from organization roles. If provided on creation, do not give either user or team.")
  public Integer getOrganization() {
    return organization;
  }

  public void setOrganization(Integer organization) {
    this.organization = organization;
  }

  public OrganizationCredentialSerializerCreate credentialType(Integer credentialType) {
    this.credentialType = credentialType;
    return this;
  }

   /**
   * Specify the type of credential you want to create. Refer to the documentation for details on each type.
   * @return credentialType
  **/
  @Schema(required = true, description = "Specify the type of credential you want to create. Refer to the documentation for details on each type.")
  public Integer getCredentialType() {
    return credentialType;
  }

  public void setCredentialType(Integer credentialType) {
    this.credentialType = credentialType;
  }

   /**
   * Get managed
   * @return managed
  **/
  @Schema(description = "")
  public String getManaged() {
    return managed;
  }

  public OrganizationCredentialSerializerCreate inputs(Object inputs) {
    this.inputs = inputs;
    return this;
  }

   /**
   * Enter inputs using either JSON or YAML syntax. Refer to the documentation for example syntax.
   * @return inputs
  **/
  @Schema(description = "Enter inputs using either JSON or YAML syntax. Refer to the documentation for example syntax.")
  public Object getInputs() {
    return inputs;
  }

  public void setInputs(Object inputs) {
    this.inputs = inputs;
  }

   /**
   * Get kind
   * @return kind
  **/
  @Schema(description = "")
  public String getKind() {
    return kind;
  }

   /**
   * Get cloud
   * @return cloud
  **/
  @Schema(description = "")
  public String getCloud() {
    return cloud;
  }

   /**
   * Get kubernetes
   * @return kubernetes
  **/
  @Schema(description = "")
  public String getKubernetes() {
    return kubernetes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationCredentialSerializerCreate organizationCredentialSerializerCreate = (OrganizationCredentialSerializerCreate) o;
    return Objects.equals(this.id, organizationCredentialSerializerCreate.id) &&
        Objects.equals(this.type, organizationCredentialSerializerCreate.type) &&
        Objects.equals(this.url, organizationCredentialSerializerCreate.url) &&
        Objects.equals(this.related, organizationCredentialSerializerCreate.related) &&
        Objects.equals(this.summaryFields, organizationCredentialSerializerCreate.summaryFields) &&
        Objects.equals(this.created, organizationCredentialSerializerCreate.created) &&
        Objects.equals(this.modified, organizationCredentialSerializerCreate.modified) &&
        Objects.equals(this.name, organizationCredentialSerializerCreate.name) &&
        Objects.equals(this.description, organizationCredentialSerializerCreate.description) &&
        Objects.equals(this.organization, organizationCredentialSerializerCreate.organization) &&
        Objects.equals(this.credentialType, organizationCredentialSerializerCreate.credentialType) &&
        Objects.equals(this.managed, organizationCredentialSerializerCreate.managed) &&
        Objects.equals(this.inputs, organizationCredentialSerializerCreate.inputs) &&
        Objects.equals(this.kind, organizationCredentialSerializerCreate.kind) &&
        Objects.equals(this.cloud, organizationCredentialSerializerCreate.cloud) &&
        Objects.equals(this.kubernetes, organizationCredentialSerializerCreate.kubernetes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, url, related, summaryFields, created, modified, name, description, organization, credentialType, managed, inputs, kind, cloud, kubernetes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationCredentialSerializerCreate {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    summaryFields: ").append(toIndentedString(summaryFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    credentialType: ").append(toIndentedString(credentialType)).append("\n");
    sb.append("    managed: ").append(toIndentedString(managed)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    cloud: ").append(toIndentedString(cloud)).append("\n");
    sb.append("    kubernetes: ").append(toIndentedString(kubernetes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
