/*
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.limix.awx.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Organization
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-25T17:26:39.970+08:00[Asia/Shanghai]")
public class Organization {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("related")
  private Object related = null;

  @SerializedName("summary_fields")
  private Object summaryFields = null;

  @SerializedName("created")
  private String created = null;

  @SerializedName("modified")
  private String modified = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = "";

  @SerializedName("max_hosts")
  private Integer maxHosts = null;

  @SerializedName("custom_virtualenv")
  private String customVirtualenv = null;

  @SerializedName("default_environment")
  private Integer defaultEnvironment = null;

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public Organization related(Object related) {
    this.related = related;
    return this;
  }

   /**
   * Get related
   * @return related
  **/
  @Schema(description = "")
  public Object getRelated() {
    return related;
  }

  public void setRelated(Object related) {
    this.related = related;
  }

  public Organization summaryFields(Object summaryFields) {
    this.summaryFields = summaryFields;
    return this;
  }

   /**
   * Get summaryFields
   * @return summaryFields
  **/
  @Schema(description = "")
  public Object getSummaryFields() {
    return summaryFields;
  }

  public void setSummaryFields(Object summaryFields) {
    this.summaryFields = summaryFields;
  }

   /**
   * Get created
   * @return created
  **/
  @Schema(description = "")
  public String getCreated() {
    return created;
  }

   /**
   * Get modified
   * @return modified
  **/
  @Schema(description = "")
  public String getModified() {
    return modified;
  }

  public Organization name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Organization description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Organization maxHosts(Integer maxHosts) {
    this.maxHosts = maxHosts;
    return this;
  }

   /**
   * Maximum number of hosts allowed to be managed by this organization.
   * minimum: 0
   * maximum: 2147483647
   * @return maxHosts
  **/
  @Schema(description = "Maximum number of hosts allowed to be managed by this organization.")
  public Integer getMaxHosts() {
    return maxHosts;
  }

  public void setMaxHosts(Integer maxHosts) {
    this.maxHosts = maxHosts;
  }

   /**
   * Local absolute file path containing a custom Python virtualenv to use
   * @return customVirtualenv
  **/
  @Schema(description = "Local absolute file path containing a custom Python virtualenv to use")
  public String getCustomVirtualenv() {
    return customVirtualenv;
  }

  public Organization defaultEnvironment(Integer defaultEnvironment) {
    this.defaultEnvironment = defaultEnvironment;
    return this;
  }

   /**
   * The default execution environment for jobs run by this organization.
   * @return defaultEnvironment
  **/
  @Schema(description = "The default execution environment for jobs run by this organization.")
  public Integer getDefaultEnvironment() {
    return defaultEnvironment;
  }

  public void setDefaultEnvironment(Integer defaultEnvironment) {
    this.defaultEnvironment = defaultEnvironment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Organization organization = (Organization) o;
    return Objects.equals(this.id, organization.id) &&
        Objects.equals(this.type, organization.type) &&
        Objects.equals(this.url, organization.url) &&
        Objects.equals(this.related, organization.related) &&
        Objects.equals(this.summaryFields, organization.summaryFields) &&
        Objects.equals(this.created, organization.created) &&
        Objects.equals(this.modified, organization.modified) &&
        Objects.equals(this.name, organization.name) &&
        Objects.equals(this.description, organization.description) &&
        Objects.equals(this.maxHosts, organization.maxHosts) &&
        Objects.equals(this.customVirtualenv, organization.customVirtualenv) &&
        Objects.equals(this.defaultEnvironment, organization.defaultEnvironment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, url, related, summaryFields, created, modified, name, description, maxHosts, customVirtualenv, defaultEnvironment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Organization {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    summaryFields: ").append(toIndentedString(summaryFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    maxHosts: ").append(toIndentedString(maxHosts)).append("\n");
    sb.append("    customVirtualenv: ").append(toIndentedString(customVirtualenv)).append("\n");
    sb.append("    defaultEnvironment: ").append(toIndentedString(defaultEnvironment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
